[theme]
base = "light"
primaryColor = "#B0893E"
backgroundColor = "#F3EEE4"
secondaryBackgroundColor = "#EBE4D6"
textColor = "#14171C"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5
maxMessageSize = 200
enableStaticServing = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
toolbarMode = "minimal"

[runner]
fastReruns = true
